name: "Bug report"
description: "Create a report to help us improve"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Before you submit a bug, please make sure that:
        - you have searched and found no existing open issue with the problem at hand
        - you don't have `"files.associations": {"*.svelte": "html"  }` inside your VSCode settings (if you can't remember ever doing that, you don't have that)
        - you are using Svelte for VS Code (NOT the old "Svelte" extension by James Birtles) and have disabled all other Svelte-related extensions to reproduce the bug
        - if it's a preprocessor related bug like "can't use typescript", did you setup `svelte-preprocess` and/or `svelte.config.js`? See the docs for more info.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: "Bug description"
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce
      placeholder: "For example, a code snippet that is treated in a way you don't expect."
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected behaviour
      placeholder: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: "Your operating system, editor, extension version etc."
      value: |
        - OS: [e.g. Windows]
        - IDE: [e.g. VSCode, Atom]
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Which package is the issue about?
      multiple: true
      options:
        - Svelte for VS Code extension
        - svelte-language-server
        - svelte2tsx
        - svelte-check

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information, eg. Screenshots
