export default [
    'oncopy',
    'oncopycapture',
    'oncut',
    'oncutcapture',
    'onpaste',
    'onpastecapture',

    // composition events
    'oncompositionend',
    'oncompositionendcapture',
    'oncompositionstart',
    'oncompositionstartcapture',
    'oncompositionupdate',
    'oncompositionupdatecapture',

    // focus events
    'onfocus',
    'onfocuscapture',
    'onblur',
    'onblurcapture',

    // form events
    'onchange',
    'onchangecapture',
    'oninput',
    'oninputcapture',
    'onreset',
    'onresetcapture',
    'onsubmit',
    'onsubmitcapture',

    // image events
    'onload',
    'onloadcapture',
    'onerror',
    'onerrorcapture',

    // keyboard events
    'onkeydown',
    'onkeydowncapture',
    'onkeypress',
    'onkeypresscapture',
    'onkeyup',
    'onkeyupcapture',

    // media events
    'onabort',
    'onabortcapture',
    'oncanplay',
    'oncanplaycapture',
    'oncanplaythrough',
    'oncanplaythroughcapture',
    'ondurationchange',
    'ondurationchangecapture',
    'onemptied',
    'onemptiedcapture',
    'onencrypted',
    'onencryptedcapture',
    'onended',
    'onendedcapture',
    'onloadeddata',
    'onloadeddatacapture',
    'onloadedmetadata',
    'onloadedmetadatacapture',
    'onloadstart',
    'onloadstartcapture',
    'onpause',
    'onpausecapture',
    'onplay',
    'onplaycapture',
    'onplaying',
    'onplayingcapture',
    'onprogress',
    'onprogresscapture',
    'onratechange',
    'onratechangecapture',
    'onseeked',
    'onseekedcapture',
    'onseeking',
    'onseekingcapture',
    'onstalled',
    'onstalledcapture',
    'onsuspend',
    'onsuspendcapture',
    'ontimeupdate',
    'ontimeupdatecapture',
    'onvolumechange',
    'onvolumechangecapture',
    'onwaiting',
    'onwaitingcapture',

    // mouseevents
    'onclick',
    'onclickcapture',
    'oncontextmenu',
    'oncontextmenucapture',
    'ondblclick',
    'ondblclickcapture',
    'ondrag',
    'ondragcapture',
    'ondragend',
    'ondragendcapture',
    'ondragenter',
    'ondragentercapture',
    'ondragexit',
    'ondragexitcapture',
    'ondragleave',
    'ondragleavecapture',
    'ondragover',
    'ondragovercapture',
    'ondragstart',
    'ondragstartcapture',
    'ondrop',
    'ondropcapture',
    'onmousedown',
    'onmousedowncapture',
    'onmouseenter',
    'onmouseleave',
    'onmousemove',
    'onmousemovecapture',
    'onmouseout',
    'onmouseoutcapture',
    'onmouseover',
    'onmouseovercapture',
    'onmouseup',
    'onmouseupcapture',

    // selection events
    'onselect',
    'onselectcapture',

    // touch events
    'ontouchcancel',
    'ontouchcancelcapture',
    'ontouchend',
    'ontouchendcapture',
    'ontouchmove',
    'ontouchmovecapture',
    'ontouchstart',
    'ontouchstartcapture',

    // ui events
    'onscroll',
    'onscrollcapture',

    // wheel events
    'onwheel',
    'onwheelcapture',

    // animation events
    'onanimationstart',
    'onanimationstartcapture',
    'onanimationend',
    'onanimationendcapture',
    'onanimationiteration',
    'onanimationiterationcapture',

    // transition events
    'ontransitionend',
    'ontransitionendcapture',
];
